name: Aprovar PRs de branches confiáveis automaticamente

on: 
  pull_request:
    types: [opened]

env:
    BRANCH: update
jobs:
    auto-aprove:
      runs-on: ubuntu-latest
        
      if: ${{github.event_name == vars.BRANCH}}

      steps: 
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Aprovar PR automaticamente
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

    
