name: Usar Secret Key

on:
    pull_request: 
      branches: [main]
    workflow_dispatch:

jobs:
    revelando-secrets:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Usar secret
          run: |
             echo "Minha chave secreta é ${{secrets.API_SECRET_KEY}}"